# Generated by Django 5.2.7 on 2025-11-02 21:38

import django.db.models.deletion
import django.utils.timezone
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('supabase_uid', models.CharField(max_length=100, unique=True)),
                ('correo', models.EmailField(max_length=200, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono_movil', models.CharField(max_length=30)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('TI', 'Tarjeta de identidad')], default='CC', max_length=30)),
                ('documento', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=12)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('foto_perfil', models.URLField(blank=True, null=True)),
                ('fecha_actualizacion_foto', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(default=users.models.empresa_default, on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.rol')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
