# Generated by Django 5.2.7 on 2025-11-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20251102_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ubicacion_actual_lat',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ubicacion_actual_long',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ultima_actualizacion_ubicacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
