# Generated by Django 5.2.7 on 2025-11-17 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usuario_ubicacion_actual_lat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='ubicacion_actual_lat',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='ubicacion_actual_long',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='ultima_actualizacion_ubicacion',
        ),
    ]
