# Generated by Django 5.2.7 on 2025-11-18 02:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=50, unique=True)),
                ('telefono_movil', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id_localidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(choices=[('Usaquén', 'Usaquén'), ('Chapinero', 'Chapinero'), ('Santa Fe', 'Santa Fe'), ('San Cristóbal', 'San Cristóbal'), ('Usme', 'Usme'), ('Tunjuelito', 'Tunjuelito'), ('Bosa', 'Bosa'), ('Kennedy', 'Kennedy'), ('Fontibón', 'Fontibón'), ('Engativá', 'Engativá'), ('Suba', 'Suba'), ('Barrios Unidos', 'Barrios Unidos'), ('Teusaquillo', 'Teusaquillo'), ('Los Mártires', 'Los Mártires'), ('Antonio Nariño', 'Antonio Nariño'), ('Puente Aranda', 'Puente Aranda'), ('La Candelaria', 'La Candelaria'), ('Rafael Uribe Uribe', 'Rafael Uribe Uribe'), ('Ciudad Bolívar', 'Ciudad Bolívar'), ('Sumapaz', 'Sumapaz')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id_barrio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('id_localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.localidad')),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id_paquete', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('tipo_paquete', models.CharField(choices=[('Grande', 'Grande'), ('Mediano', 'Mediano'), ('Pequeno', 'Pequeño'), ('Refrigerado', 'Refrigerado'), ('Fragil', 'Fragil')], default='Mediano', max_length=15)),
                ('estado_paquete', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Asignado', 'Asignado'), ('En ruta', 'En ruta'), ('Entregado', 'Entregado'), ('Fallido', 'Fallido')], default='Pendiente', max_length=12)),
                ('largo', models.FloatField()),
                ('ancho', models.FloatField()),
                ('alto', models.FloatField()),
                ('peso', models.FloatField()),
                ('valor_declarado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField()),
                ('imagen', models.URLField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, max_length=200, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True)),
                ('direccion_entrega', models.CharField(max_length=200)),
                ('orden_entrega', models.IntegerField(blank=True, null=True)),
                ('barrio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='packages.barrio')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paquetes', to='packages.cliente')),
                ('ruta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paquetes', to='routes.ruta')),
            ],
            options={
                'db_table': 'paquete',
            },
        ),
    ]
