# Generated by Django 5.2.7 on 2025-11-18 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='barrio',
            table='barrio',
        ),
        migrations.AlterModelTable(
            name='cliente',
            table='cliente',
        ),
        migrations.AlterModelTable(
            name='localidad',
            table='localidad',
        ),
    ]
