# Generated by Django 5.2.7 on 2025-11-20 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_alter_barrio_table_alter_cliente_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paquete',
            name='barrio',
        ),
        migrations.AddField(
            model_name='paquete',
            name='localidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='packages.localidad'),
        ),
        migrations.DeleteModel(
            name='Barrio',
        ),
    ]
