# Generated by Django 5.2.7 on 2025-11-20 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_remove_paquete_barrio_paquete_localidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paquete',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='paquete',
            name='observacion',
        ),
        migrations.AlterField(
            model_name='paquete',
            name='localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='packages.localidad'),
        ),
    ]
