# Generated by Django 5.2.7 on 2025-11-20 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_remove_paquete_imagen_remove_paquete_observacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='localidad',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='packages.localidad'),
        ),
    ]
