# Generated by Django 5.2.7 on 2025-11-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_alter_paquete_localidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='destinatario_apellido',
            field=models.CharField(default='Sin apellido', max_length=20),
        ),
        migrations.AddField(
            model_name='paquete',
            name='destinatario_correo',
            field=models.EmailField(default='Sin correo', max_length=50),
        ),
        migrations.AddField(
            model_name='paquete',
            name='destinatario_nombre',
            field=models.CharField(default='Sin nombre', max_length=20),
        ),
        migrations.AddField(
            model_name='paquete',
            name='destinatario_telefono',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
