# Generated by Django 5.2.7 on 2025-11-17 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0002_driver_ubicacion_actual_lat_and_more'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id_ruta', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Asignada', 'Asignada'), ('En ruta', 'En ruta'), ('Completada', 'Completada'), ('Fallida', 'Fallida')], default='Pendiente', max_length=15)),
                ('conductor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ruta_actual', to='drivers.driver')),
                ('vehiculo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ruta_actual', to='vehicles.vehiculo')),
            ],
        ),
    ]
