# Generated by Django 5.2.7 on 2025-11-20 06:10

import django.db.models.deletion
import django.utils.timezone
import routes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_driver_ubicacion_actual_lat_and_more'),
        ('packages', '0004_remove_paquete_imagen_remove_paquete_observacion_and_more'),
        ('routes', '0001_initial'),
        ('vehicles', '0002_alter_vehiculo_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ruta',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.AddField(
            model_name='ruta',
            name='codigo_manifiesto',
            field=models.CharField(default=routes.models.generar_codigo_manifiesto, max_length=20),
        ),
        migrations.AddField(
            model_name='ruta',
            name='distancia_total_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ruta',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='paquetes_entregados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ruta',
            name='paquetes_fallidos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ruta',
            name='ruta_optimizada',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='tiempo_estimado_minutos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='total_paquetes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='conductor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas', to='drivers.driver'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='vehiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas', to='vehicles.vehiculo'),
        ),
        migrations.AlterModelTable(
            name='ruta',
            table='ruta',
        ),
        migrations.CreateModel(
            name='EntregaPaquete',
            fields=[
                ('id_entrega', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('Entregado', 'Entregado'), ('Fallido', 'Fallido')], max_length=10)),
                ('fecha_entrega', models.DateTimeField(default=django.utils.timezone.now)),
                ('imagen', models.URLField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('lat_entrega', models.DecimalField(decimal_places=8, max_digits=10)),
                ('lng_entrega', models.DecimalField(decimal_places=8, max_digits=11)),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='packages.paquete')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='routes.ruta')),
            ],
        ),
    ]
