# Generated by Django 5.2.7 on 2025-11-20 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_alter_ruta_options_ruta_codigo_manifiesto_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='entregapaquete',
            table='entrega_paquete',
        ),
    ]
