# Generated by Django 5.2.7 on 2025-11-22 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_alter_entregapaquete_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta',
            name='vehiculo',
        ),
    ]
