# Generated by Django 5.2.7 on 2025-11-26 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_remove_ruta_vehiculo'),
        ('vehicles', '0004_alter_vehiculo_placa'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='vehiculo_usado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas_realizadas', to='vehicles.vehiculo'),
        ),
    ]
