# Generated by Django 5.2.7 on 2025-11-06 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20251102_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id_conductor', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('en_ruta', 'En ruta'), ('no_disponible', 'No disponible')], default='disponible', max_length=20)),
                ('conductor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estado_operativo', to='users.usuario')),
            ],
            options={
                'db_table': 'estado_conductor',
            },
        ),
    ]
