# Generated by Django 5.2.7 on 2025-11-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='ubicacion_actual_lat',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='ubicacion_actual_lng',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='ultima_actualizacion_ubicacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
