# Generated by Django 5.2.7 on 2025-11-22 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_driver_ubicacion_actual_lat_and_more'),
        ('vehicles', '0003_alter_vehiculo_estado_alter_vehiculo_placa'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='vehiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='vehicles.vehiculo'),
        ),
    ]
