# Generated by Django 5.2.7 on 2025-11-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_driver_vehiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Asignado', 'Asignado'), ('En ruta', 'En ruta'), ('No disponible', 'No disponible')], default='Disponible', max_length=20),
        ),
    ]
