# Generated by Django 5.2.7 on 2025-12-04 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_alter_driver_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='base_lat',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='base_lng',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='direccion_actual',
            field=models.TextField(blank=True, help_text='Dirección textual actual (geocoding inverso)', null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='direccion_base',
            field=models.TextField(blank=True, help_text='Dirección textual de la base/almacén/bodega', null=True),
        ),
    ]
