# Generated by Django 5.2.7 on 2025-11-09 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id_novedad', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('problemas_entrega', 'Problemas de entrega'), ('problemas_destinatario', 'Problemas destinatario'), ('demoras_operativas', 'Demoras operativas'), ('problemas_documentacion', 'Problemas documentaciòn')], max_length=40)),
                ('descripcion', models.TextField(max_length=200)),
                ('imagen', models.URLField(blank=True, null=True)),
                ('fecha_novedad', models.DateTimeField(auto_now=True, null=True)),
                ('leida', models.BooleanField(default=False)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novedades', to='drivers.driver')),
            ],
            options={
                'db_table': 'novedades',
                'ordering': ['-fecha_novedad'],
            },
        ),
    ]
