# Generated by Django 5.2.7 on 2025-11-09 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedad',
            name='fecha_novedad',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 11, 9, 19, 47, 7, 795323, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
