# Generated by Django 5.2.7 on 2025-11-17 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('Camion', 'Camión'), ('Furgon', 'Furgón'), ('Camioneta', 'Camioneta'), ('Moto', 'Moto')], default='Furgon', max_length=10)),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('imagen', models.URLField()),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('En ruta', 'En ruta'), ('No disponible', 'No disponible')], default='Disponible', max_length=15)),
            ],
        ),
    ]
