# Generated by Django 5.2.7 on 2025-11-17 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vehiculo',
            table='vehiculo',
        ),
    ]
