# Generated by Django 5.2.7 on 2025-11-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_vehiculo_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Asignado', 'Asignado'), ('En ruta', 'En ruta'), ('No disponible', 'No disponible')], default='Disponible', max_length=15),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
