# Generated by Django 5.2.7 on 2025-11-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_alter_vehiculo_estado_alter_vehiculo_placa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
