"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import environ

# Inicializar django-environ
env = environ.Env(
    DEBUG=(bool, False)
)


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent





# --- .env ---
# Primero, si existe un .env base en el proyecto (solo para controlar ENVIRONMENT), léelo.
base_env = BASE_DIR / ".env"
if base_env.exists():
    environ.Env.read_env(base_env)

# Ahora obten el valor ENVIRONMENT (primero mira variable del sistema, luego .env base, si no -> 'development')
environment = env('ENVIRONMENT', default='development')

# Carga el archivo específico de entorno si existe
env_file = BASE_DIR / f".env.{environment}"
if env_file.exists():
    environ.Env.read_env(env_file)




# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)



# Autorizaciòn de Cors
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[])
CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=[])


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_spectacular',
    'empresa',
    'users',
    'drivers',
    'novedades',
    'vehicles',
    'packages',
    'routes',
    'assistants'
]

# settings/base.py
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'config.disable_csrf.DisableCSRFMiddleware',
    'users.middleware.SupabaseAuthMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
import pymysql
pymysql.install_as_MySQLdb()




import dj_database_url
import os

# Database - Priorizar MYSQL_URL de Railway
mysql_url = os.environ.get('MYSQL_URL')

if mysql_url:
    # Producción - Railway proporciona MYSQL_URL automáticamente
    DATABASES = {
        'default': dj_database_url.parse(mysql_url, conn_max_age=600)
    }
else:
    # Desarrollo local - usar variables individuales
    try:
        DATABASES = {
            'default': dj_database_url.config(
                default=f"mysql://{env('DB_USER')}:{env('DB_PASSWORD')}@{env('DB_HOST')}:{env('DB_PORT')}/{env('DB_NAME')}",
                conn_max_age=600,
                conn_health_checks=True,
            )
        }
    except Exception as e:
        # Fallback si no hay variables de DB configuradas
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }




# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Whitenoise para servir archivos estáticos
MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesBackend",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'




""" # Autorizacion de cors - Esta en development
CORS_ALLOWED_ORIGINS = []  

ALLOWED_HOSTS = []
"""


# Documentación
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}


# Métadatos basicos del proyecto para la api
SPECTACULAR_SETTINGS = {
    'TITLE': 'Documentación API de Route Manager',
    'DESCRIPTION': 'Esta es una documentación hecha automaticamente por drf_spectacular para Route Manager',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    # OTHER SETTINGS
}


#Supabase
SUPABASE_URL = env('SUPABASE_URL')
SUPABASE_KEY = env('SUPABASE_SERVICE_ROLE_KEY')
SUPABASE_BUCKET = env('SUPABASE_BUCKET', default='images')

# Geocoding
GEOCODING_KEY = env('GEOCODING_KEY')

# modelo de AI - Groq
GROQ_API_KEY = env('GROQ_API_KEY')



# No lo usare de momento porque nisiquiera se que es
""" LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
} """

