# Generated by Django 5.2.7 on 2025-11-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nit', models.CharField(max_length=30, unique=True)),
                ('nombre_empresa', models.CharField(max_length=50)),
                ('telefono_empresa', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'empresa',
            },
        ),
    ]
