# Generated by Django 5.2.7 on 2025-11-03 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='nombre_empresa',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefono_empresa',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
